<<<<<<< HEAD
<<<<<<< HEAD
# name: eeei
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.7.2

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8
#   # excel: ^3.0.0
#   flutter_screenutil: ^5.5.3
#   google_fonts: ^6.1.0
#   http: ^1.1.0
#   # shared_preferences: ^2.0.15
#   url_launcher: ^6.0.20 # تم إضافة هذا السطر
#   font_awesome_flutter: ^10.7.0 
#   animate_do: ^3.0.0
#   animations: ^2.0.7

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/EIcon2.png
#     - assets/Logo.jpeg
#     - assets/chatbot.jpg
#     - assets/AiChatboot.jpg
#     - assets/data/types.json
#     - assets/data/fields.json
#     - assets/data/companies.json
#     - assets/CompaniesLogo/
#     - assets/images/

    








name: eeei
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.3
  google_fonts: ^6.1.0
  http: ^1.1.0
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.0.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # تم إضافة هذا السطر

flutter:
  uses-material-design: true
  assets:
    - assets/EIcon2.png
    - assets/2025-09-16 (1).png
    
    - assets/eeeiicon.png
  

    - assets/data/types.json
    - assets/data/fields.json
    - assets/data/companies.json
   
    - assets/images/
    - assets/data/companies_normalized.json
    - assets/data/company_fields.json
    - assets/logoDar.png
    - assets/logomagic.jpeg

# --- الأيقونة ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/EIcon2.png" # هنا مسار الأيقونة
=======
# name: eeei
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.7.2

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8
#   # excel: ^3.0.0
#   flutter_screenutil: ^5.5.3
#   google_fonts: ^6.1.0
#   http: ^1.1.0
#   # shared_preferences: ^2.0.15
#   url_launcher: ^6.0.20 # تم إضافة هذا السطر
#   font_awesome_flutter: ^10.7.0 
#   animate_do: ^3.0.0
#   animations: ^2.0.7

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/EIcon2.png
#     - assets/Logo.jpeg
#     - assets/chatbot.jpg
#     - assets/AiChatboot.jpg
#     - assets/data/types.json
#     - assets/data/fields.json
#     - assets/data/companies.json
#     - assets/CompaniesLogo/
#     - assets/images/

    








name: eeei
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.3
  google_fonts: ^6.1.0
  http: ^1.1.0
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.0.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # تم إضافة هذا السطر

flutter:
  uses-material-design: true
  assets:
    - assets/EIcon2.png
    - assets/2025-09-16 (1).png
    
    - assets/eeeiicon.png
  

    - assets/data/types.json
    - assets/data/fields.json
    - assets/data/companies.json
   
    - assets/images/
    - assets/data/companies_normalized.json
    - assets/data/company_fields.json
    - assets/logoDar.png
    - assets/logomagic.jpeg

# --- الأيقونة ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/EIcon2.png" # هنا مسار الأيقونة
>>>>>>> 1c9d6fa1b5b38a5d7b2e992dec86ee7603b5ab1d
  min_sdk_android: 21
=======
# name: eeei
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.7.2

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8
#   # excel: ^3.0.0
#   flutter_screenutil: ^5.5.3
#   google_fonts: ^6.1.0
#   http: ^1.1.0
#   # shared_preferences: ^2.0.15
#   url_launcher: ^6.0.20 # تم إضافة هذا السطر
#   font_awesome_flutter: ^10.7.0 
#   animate_do: ^3.0.0
#   animations: ^2.0.7

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/EIcon2.png
#     - assets/Logo.jpeg
#     - assets/chatbot.jpg
#     - assets/AiChatboot.jpg
#     - assets/data/types.json
#     - assets/data/fields.json
#     - assets/data/companies.json
#     - assets/CompaniesLogo/
#     - assets/images/

    








name: eeei
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.3
  google_fonts: ^6.1.0
  http: ^1.1.0
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.0.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # تم إضافة هذا السطر

flutter:
  uses-material-design: true
  assets:
    - assets/EIcon2.png
    - assets/2025-09-16 (1).png
    
    - assets/eeeiicon.png
  

    - assets/data/types.json
    - assets/data/fields.json
    - assets/data/companies.json
   
    - assets/images/
    - assets/data/companies_normalized.json
    - assets/data/company_fields.json
    - assets/logoDar.png
    - assets/logomagic.jpeg

# --- الأيقونة ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/EIcon2.png" # هنا مسار الأيقونة
  min_sdk_android: 21
>>>>>>> 54843990ae95a90b62d11fd587f58a4fb0f01c4d
